### PR TITLE
Turn stateful to stateless components

### PR DESCRIPTION
**Pull request by fakiolinho**
- Turned stateful to stateless components
- Upgraded dependencies
- Changed babel setup in .babelrc
- Extended airbnb configuration in .eslintrc (not sure if you wanted this but it was a nightmare to update previous setup because of many expired / updated rules)
- Applied some minor changes to make eslint pass:
  - used whenever possible `const` instead of `let` variables
  - replaced `for..in` with `Object.keys(obj).forEach(...)`
  - declared propTypes for everything even for `children` and `className`
- Changed the way the 3 components are exported
- Tweaked Jest setup in package.json
- Added enzyme shallow testing in unit tests

### CODE REVIEW

**Comment by nkt** [comment]
Awesome, thanks!
Maybe we should completely migrate to Airbnb eslint config?

**Comment by fakiolinho** [comment]
Sure!!! So you mean we should just extend Airbnb rules and keep override rules to the bare minimum and if possible to 0?

**Comment by nkt** [comment]
@fakiolinho yep

**Comment by cmcrothers** [comment]
@nkt any update on merging this? react-flexbox grid is now one of my last blocking v16 upgrade packages because of `PropTypes` and `createClass`

**Comment by nkt** [comment]
Sorry for such delay. I've published this as `1.0.0`.

**Pull request merged**
